name: build-application

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PWD }}
        repository: asizikov/echo-api
        tag_with_ref: true
        tag_with_sha: true
        path: src/Echo.Api
        add_git_labels: true
    - name: Azure CLI Login
      uses: Azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Create ACI resouce
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          az container create -g rg-aci-echo -l westeurope -n aci-echo-api --image asizikov/echo-api:latest --cpu 1 --memory 0.5 --dns-name-label echo-api --ip-address Public
      
